### ISSUE TITLE
IE 11 initCustomEvent (argument not optional)

### ISSUE THREAD

**Issue by internetchris** [ScottPolhemus/scroll-in#2]
It seems anywhere this is used `event.initCustomEvent('scroll-in', true, true);` IE 11 if throwing an error. and causing the execution of JS to stop

I tried it manually using IE 11 on Win7 and got the following: 

![screen shot on 2016-08-03 at 17-09-11](https://cloud.githubusercontent.com/assets/45402/17385228/9e58ebd8-599e-11e6-9dfc-37d592e932c6.png)

if I simply added  `event.initCustomEvent('scroll-in', true, true, {});` it worked fine.

**Comment by internetchris** [comment]
@ScottPolhemus - I can create a fork of your project to move on, but wanted to see if you had a timeline on fixing this? Thanks!

**Comment by internetchris** [comment]
That 4th argument in initCustomEvent ( even it it's `{}` ) must be passed it seems.

**Comment by ScottPolhemus** [comment]
Hi @internetchris, thanks for the info! If you want to fork and create a PR I'd happily merge that in & create a new NPM release. If I don't hear back by this weekend I'll probably fix it myself, as the change is rather trivial, just want to give you a chance to contribute directly if you'd like.

**Comment by internetchris** [comment]
Hey Scott,

Thanks, I'm happy to fork it, but won't be available until Tuesday, so if
you get to it first all the better!

Chris

**Comment by internetchris** [comment]
Here you go: https://github.com/ScottPolhemus/scroll-in/pull/3

**Comment by ScottPolhemus** [comment]
Merged!
